import React from 'react';

import { getFormById } from '@/actions/form';
import { VisitButton } from '@/components/buttons/visit-button';
import { FormShareLink } from '@/components/form-builder/form-share-link';

export const metadata = {
  title: 'DnD Forms | Form Details',
  description: 'Generated by create next app',
};

interface FormDetailsPageProps {
  params: {
    id: string;
  };
}

export default async function FormDetailsPage({
  params,
}: Readonly<FormDetailsPageProps>) {
  const { id } = params;

  const form = await getFormById(Number(id));
  if (!form) {
    throw new Error('Form not found');
  }

  const { visits, submissions } = form;

  const submissionRate = visits > 0 ? (submissions / visits) * 100 : 0;
  const bounceRate = 100 - submissionRate;

  return (
    <>
      <div className="py-10 border-b border-muted">
        <div className="flex justify-between container">
          <h1 className="text-4xl font-bold truncate">{form.name}</h1>
          <VisitButton shareUrl={form.shareURL} />
        </div>
      </div>
      <div className="py-4 border-b border-muted">
        <div className="container flex gap-2 items-center justify-between">
          <FormShareLink shareUrl={form.shareURL} />
        </div>
      </div>
    </>
  );
}
