import React from 'react';

import { getFormById } from '@/actions/form';
import { FormBuilder } from '@/components/form-builder/form-builder';

export const metadata = {
  title: 'DnD Forms | Form Details',
  description: 'Generated by create next app',
};

interface FormPageProps {
  params: {
    id: string;
  };
}

export default async function FormPage({ params }: Readonly<FormPageProps>) {
  const { id } = params;

  const form = await getFormById(Number(id));
  if (!form) {
    throw new Error('Form not found');
  }

  return <>Details</>;
}
