import React from 'react';

export const metadata = {
  title: 'DnD Forms | Builder',
  description: 'Generated by create next app',
};

interface BuilderLayoutProps {
  params: {
    id: string;
  };
}

export default function BuilderPage({ params }: Readonly<BuilderLayoutProps>) {
  return <div className="container pt-4">{params.id}</div>;
}
