import React from 'react';

import { getFormById } from '@/actions/form';
import { FormBuilder } from '@/components/form-builder/form-builder';

export const metadata = {
  title: 'DnD Forms | Builder',
  description: 'Generated by create next app',
};

interface BuilderLayoutProps {
  params: {
    id: string;
  };
}

export default async function BuilderPage({
  params,
}: Readonly<BuilderLayoutProps>) {
  const { id } = params;

  const form = await getFormById(Number(id));
  if (!form) {
    throw new Error('Form not found');
  }

  return <FormBuilder form={form} />;
}
