import React from 'react';

export const metadata = {
  title: 'DnD Forms',
  description: 'Generated by create next app',
};

export default function Dashboard() {
  return (
    <div>
      <h1>Dashboard</h1>
    </div>
  );
}
